
[compat]
Adapt = "^3"
CUDA = "3"
CUDAKernels = "0.2, 0.3"
Crayons = "^4"
CubedSphere = "0.1"
FFTW = "^1"
Glob = "1.3"
JLD2 = "^0.4"
KernelAbstractions = "0.6, 0.7"
MPI = "0.16, 0.17, 0.18, 0.19"
NCDatasets = "^0.10, ^0.11"
OffsetArrays = "^1.4"
OrderedCollections = "^1.1"
PencilFFTs = "0.12"
Rotations = "1.0"
SafeTestsets = "0.0.1"
SeawaterPolynomials = "^0.2"
StructArrays = "0.4, 0.5, 0.6"
Tullio = "0.2, 0.3"
julia = "^1.6"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
TimesDates = "bdfc003b-8df8-5c39-adcd-3a9087f5df4a"

[targets]
test = ["BenchmarkTools", "Coverage", "DataDeps", "InteractiveUtils", "Plots", "Test", "TimerOutputs", "TimesDates"]
